package com.udea.dto;
// Generated 26/11/2016 02:55:03 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Asiento generated by hbm2java
 */
@Entity
@Table(name="ASIENTO"
    ,schema="ROOT"
)
public class Asiento  implements java.io.Serializable {


     private String codigo;
     private String fila;
     private String numerosilla;
     private String salaFk;

    public Asiento() {
    }

    public Asiento(String codigo, String fila, String numerosilla, String salaFk) {
       this.codigo = codigo;
       this.fila = fila;
       this.numerosilla = numerosilla;
       this.salaFk = salaFk;
    }
   
     @Id 

    
    @Column(name="CODIGO", unique=true, nullable=false, length=15)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="FILA", nullable=false, length=5)
    public String getFila() {
        return this.fila;
    }
    
    public void setFila(String fila) {
        this.fila = fila;
    }

    
    @Column(name="NUMEROSILLA", nullable=false, length=5)
    public String getNumerosilla() {
        return this.numerosilla;
    }
    
    public void setNumerosilla(String numerosilla) {
        this.numerosilla = numerosilla;
    }

    
    @Column(name="SALA_FK", nullable=false, length=15)
    public String getSalaFk() {
        return this.salaFk;
    }
    
    public void setSalaFk(String salaFk) {
        this.salaFk = salaFk;
    }




}


