package com.udea.dto;
// Generated 26/11/2016 02:55:03 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cartelera generated by hbm2java
 */
@Entity
@Table(name="CARTELERA"
    ,schema="ROOT"
)
public class Cartelera  implements java.io.Serializable {


     private String codigo;
     private Date fechaestreno;
     private Date fechasalida;
     private String peliculaFk;
     private String sucursalFk;

    public Cartelera() {
    }

    public Cartelera(String codigo, Date fechaestreno, Date fechasalida, String peliculaFk, String sucursalFk) {
       this.codigo = codigo;
       this.fechaestreno = fechaestreno;
       this.fechasalida = fechasalida;
       this.peliculaFk = peliculaFk;
       this.sucursalFk = sucursalFk;
    }
   
     @Id 

    
    @Column(name="CODIGO", unique=true, nullable=false, length=15)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHAESTRENO", nullable=false, length=10)
    public Date getFechaestreno() {
        return this.fechaestreno;
    }
    
    public void setFechaestreno(Date fechaestreno) {
        this.fechaestreno = fechaestreno;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHASALIDA", nullable=false, length=10)
    public Date getFechasalida() {
        return this.fechasalida;
    }
    
    public void setFechasalida(Date fechasalida) {
        this.fechasalida = fechasalida;
    }

    
    @Column(name="PELICULA_FK", nullable=false, length=15)
    public String getPeliculaFk() {
        return this.peliculaFk;
    }
    
    public void setPeliculaFk(String peliculaFk) {
        this.peliculaFk = peliculaFk;
    }

    
    @Column(name="SUCURSAL_FK", nullable=false, length=15)
    public String getSucursalFk() {
        return this.sucursalFk;
    }
    
    public void setSucursalFk(String sucursalFk) {
        this.sucursalFk = sucursalFk;
    }




}


