package com.udea.dto;
// Generated 26/11/2016 02:55:03 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Clasificacion generated by hbm2java
 */
@Entity
@Table(name="CLASIFICACION"
    ,schema="ROOT"
)
public class Clasificacion  implements java.io.Serializable {


     private String codigo;
     private int edad;

    public Clasificacion() {
    }

    public Clasificacion(String codigo, int edad) {
       this.codigo = codigo;
       this.edad = edad;
    }
   
     @Id 

    
    @Column(name="CODIGO", unique=true, nullable=false, length=15)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="EDAD", nullable=false)
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }




}


