package com.udea.dto;
// Generated 26/11/2016 02:55:03 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Formato generated by hbm2java
 */
@Entity
@Table(name="FORMATO"
    ,schema="ROOT"
)
public class Formato  implements java.io.Serializable {


     private String codigo;
     private String descripcion;
     private String tipo;
     private String idiomaaudio;
     private String idiomasubtitulo;

    public Formato() {
    }

    public Formato(String codigo, String descripcion, String tipo, String idiomaaudio, String idiomasubtitulo) {
       this.codigo = codigo;
       this.descripcion = descripcion;
       this.tipo = tipo;
       this.idiomaaudio = idiomaaudio;
       this.idiomasubtitulo = idiomasubtitulo;
    }
   
     @Id 

    
    @Column(name="CODIGO", unique=true, nullable=false, length=15)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="DESCRIPCION", nullable=false, length=150)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="TIPO", nullable=false, length=50)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    
    @Column(name="IDIOMAAUDIO", nullable=false, length=15)
    public String getIdiomaaudio() {
        return this.idiomaaudio;
    }
    
    public void setIdiomaaudio(String idiomaaudio) {
        this.idiomaaudio = idiomaaudio;
    }

    
    @Column(name="IDIOMASUBTITULO", nullable=false, length=15)
    public String getIdiomasubtitulo() {
        return this.idiomasubtitulo;
    }
    
    public void setIdiomasubtitulo(String idiomasubtitulo) {
        this.idiomasubtitulo = idiomasubtitulo;
    }




}


