package com.udea.dto;
// Generated 26/11/2016 02:55:03 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Formatoxpelicula generated by hbm2java
 */
@Entity
@Table(name="FORMATOXPELICULA"
    ,schema="ROOT"
)
public class Formatoxpelicula  implements java.io.Serializable {


     private FormatoxpeliculaId id;

    public Formatoxpelicula() {
    }

    public Formatoxpelicula(FormatoxpeliculaId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="peliculaFk", column=@Column(name="PELICULA_FK", nullable=false, length=15) ), 
        @AttributeOverride(name="formatoFk", column=@Column(name="FORMATO_FK", nullable=false, length=15) ) } )
    public FormatoxpeliculaId getId() {
        return this.id;
    }
    
    public void setId(FormatoxpeliculaId id) {
        this.id = id;
    }




}


