package com.udea.dto;
// Generated 26/11/2016 02:55:03 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FormatoxpeliculaId generated by hbm2java
 */
@Embeddable
public class FormatoxpeliculaId  implements java.io.Serializable {


     private String peliculaFk;
     private String formatoFk;

    public FormatoxpeliculaId() {
    }

    public FormatoxpeliculaId(String peliculaFk, String formatoFk) {
       this.peliculaFk = peliculaFk;
       this.formatoFk = formatoFk;
    }
   


    @Column(name="PELICULA_FK", nullable=false, length=15)
    public String getPeliculaFk() {
        return this.peliculaFk;
    }
    
    public void setPeliculaFk(String peliculaFk) {
        this.peliculaFk = peliculaFk;
    }


    @Column(name="FORMATO_FK", nullable=false, length=15)
    public String getFormatoFk() {
        return this.formatoFk;
    }
    
    public void setFormatoFk(String formatoFk) {
        this.formatoFk = formatoFk;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FormatoxpeliculaId) ) return false;
		 FormatoxpeliculaId castOther = ( FormatoxpeliculaId ) other; 
         
		 return ( (this.getPeliculaFk()==castOther.getPeliculaFk()) || ( this.getPeliculaFk()!=null && castOther.getPeliculaFk()!=null && this.getPeliculaFk().equals(castOther.getPeliculaFk()) ) )
 && ( (this.getFormatoFk()==castOther.getFormatoFk()) || ( this.getFormatoFk()!=null && castOther.getFormatoFk()!=null && this.getFormatoFk().equals(castOther.getFormatoFk()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPeliculaFk() == null ? 0 : this.getPeliculaFk().hashCode() );
         result = 37 * result + ( getFormatoFk() == null ? 0 : this.getFormatoFk().hashCode() );
         return result;
   }   


}


