package com.udea.dto;
// Generated 26/11/2016 02:55:03 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Funcion generated by hbm2java
 */
@Entity
@Table(name="FUNCION"
    ,schema="ROOT"
)
public class Funcion  implements java.io.Serializable {


     private String codigo;
     private Date fecha;
     private Date horainicio;
     private Date horafin;
     private double precio;
     private String carteleraPk;
     private String formatoPk;
     private String salaFk;

    public Funcion() {
    }

    public Funcion(String codigo, Date fecha, Date horainicio, Date horafin, double precio, String carteleraPk, String formatoPk, String salaFk) {
       this.codigo = codigo;
       this.fecha = fecha;
       this.horainicio = horainicio;
       this.horafin = horafin;
       this.precio = precio;
       this.carteleraPk = carteleraPk;
       this.formatoPk = formatoPk;
       this.salaFk = salaFk;
    }
   
     @Id 

    
    @Column(name="CODIGO", unique=true, nullable=false, length=15)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="HORAINICIO", nullable=false, length=8)
    public Date getHorainicio() {
        return this.horainicio;
    }
    
    public void setHorainicio(Date horainicio) {
        this.horainicio = horainicio;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="HORAFIN", nullable=false, length=8)
    public Date getHorafin() {
        return this.horafin;
    }
    
    public void setHorafin(Date horafin) {
        this.horafin = horafin;
    }

    
    @Column(name="PRECIO", nullable=false, precision=52, scale=0)
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }

    
    @Column(name="CARTELERA_PK", nullable=false, length=15)
    public String getCarteleraPk() {
        return this.carteleraPk;
    }
    
    public void setCarteleraPk(String carteleraPk) {
        this.carteleraPk = carteleraPk;
    }

    
    @Column(name="FORMATO_PK", nullable=false, length=15)
    public String getFormatoPk() {
        return this.formatoPk;
    }
    
    public void setFormatoPk(String formatoPk) {
        this.formatoPk = formatoPk;
    }

    
    @Column(name="SALA_FK", nullable=false, length=15)
    public String getSalaFk() {
        return this.salaFk;
    }
    
    public void setSalaFk(String salaFk) {
        this.salaFk = salaFk;
    }




}


