package com.udea.dto;
// Generated 26/11/2016 02:55:03 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * General generated by hbm2java
 */
@Entity
@Table(name="GENERAL"
    ,schema="ROOT"
)
public class General  implements java.io.Serializable {


     private String asientoFk;

    public General() {
    }

    public General(String asientoFk) {
       this.asientoFk = asientoFk;
    }
   
     @Id 

    
    @Column(name="ASIENTO_FK", unique=true, nullable=false, length=15)
    public String getAsientoFk() {
        return this.asientoFk;
    }
    
    public void setAsientoFk(String asientoFk) {
        this.asientoFk = asientoFk;
    }




}


