package com.udea.dto;
// Generated 26/11/2016 02:55:03 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Integrante generated by hbm2java
 */
@Entity
@Table(name="INTEGRANTE"
    ,schema="ROOT"
)
public class Integrante  implements java.io.Serializable {


     private String identificacion;
     private String nombre;
     private String apellidos;
     private int edad;

    public Integrante() {
    }

    public Integrante(String identificacion, String nombre, String apellidos, int edad) {
       this.identificacion = identificacion;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.edad = edad;
    }
   
     @Id 

    
    @Column(name="IDENTIFICACION", unique=true, nullable=false, length=15)
    public String getIdentificacion() {
        return this.identificacion;
    }
    
    public void setIdentificacion(String identificacion) {
        this.identificacion = identificacion;
    }

    
    @Column(name="NOMBRE", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="APELLIDOS", nullable=false, length=50)
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    
    @Column(name="EDAD", nullable=false)
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }




}


