package com.udea.dto;
// Generated 26/11/2016 02:55:03 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IntegrantexelencoId generated by hbm2java
 */
@Embeddable
public class IntegrantexelencoId  implements java.io.Serializable {


     private String elencoFk;
     private String integranteFk;

    public IntegrantexelencoId() {
    }

    public IntegrantexelencoId(String elencoFk, String integranteFk) {
       this.elencoFk = elencoFk;
       this.integranteFk = integranteFk;
    }
   


    @Column(name="ELENCO_FK", nullable=false, length=15)
    public String getElencoFk() {
        return this.elencoFk;
    }
    
    public void setElencoFk(String elencoFk) {
        this.elencoFk = elencoFk;
    }


    @Column(name="INTEGRANTE_FK", nullable=false, length=15)
    public String getIntegranteFk() {
        return this.integranteFk;
    }
    
    public void setIntegranteFk(String integranteFk) {
        this.integranteFk = integranteFk;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IntegrantexelencoId) ) return false;
		 IntegrantexelencoId castOther = ( IntegrantexelencoId ) other; 
         
		 return ( (this.getElencoFk()==castOther.getElencoFk()) || ( this.getElencoFk()!=null && castOther.getElencoFk()!=null && this.getElencoFk().equals(castOther.getElencoFk()) ) )
 && ( (this.getIntegranteFk()==castOther.getIntegranteFk()) || ( this.getIntegranteFk()!=null && castOther.getIntegranteFk()!=null && this.getIntegranteFk().equals(castOther.getIntegranteFk()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getElencoFk() == null ? 0 : this.getElencoFk().hashCode() );
         result = 37 * result + ( getIntegranteFk() == null ? 0 : this.getIntegranteFk().hashCode() );
         return result;
   }   


}


