package com.udea.dto;
// Generated 26/11/2016 02:55:03 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pelicula generated by hbm2java
 */
@Entity
@Table(name="PELICULA"
    ,schema="ROOT"
)
public class Pelicula  implements java.io.Serializable {


     private String codigo;
     private int duracion;
     private String estado;
     private Date fechaestreno;
     private String sinopsis;
     private String titulo;
     private String clasificacionPk;
     private String generoPk;

    public Pelicula() {
    }

    public Pelicula(String codigo, int duracion, String estado, Date fechaestreno, String sinopsis, String titulo, String clasificacionPk, String generoPk) {
       this.codigo = codigo;
       this.duracion = duracion;
       this.estado = estado;
       this.fechaestreno = fechaestreno;
       this.sinopsis = sinopsis;
       this.titulo = titulo;
       this.clasificacionPk = clasificacionPk;
       this.generoPk = generoPk;
    }
   
     @Id 

    
    @Column(name="CODIGO", unique=true, nullable=false, length=15)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="DURACION", nullable=false)
    public int getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(int duracion) {
        this.duracion = duracion;
    }

    
    @Column(name="ESTADO", nullable=false, length=40)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHAESTRENO", nullable=false, length=10)
    public Date getFechaestreno() {
        return this.fechaestreno;
    }
    
    public void setFechaestreno(Date fechaestreno) {
        this.fechaestreno = fechaestreno;
    }

    
    @Column(name="SINOPSIS", nullable=false, length=500)
    public String getSinopsis() {
        return this.sinopsis;
    }
    
    public void setSinopsis(String sinopsis) {
        this.sinopsis = sinopsis;
    }

    
    @Column(name="TITULO", nullable=false, length=100)
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    
    @Column(name="CLASIFICACION_PK", nullable=false, length=15)
    public String getClasificacionPk() {
        return this.clasificacionPk;
    }
    
    public void setClasificacionPk(String clasificacionPk) {
        this.clasificacionPk = clasificacionPk;
    }

    
    @Column(name="GENERO_PK", nullable=false, length=15)
    public String getGeneroPk() {
        return this.generoPk;
    }
    
    public void setGeneroPk(String generoPk) {
        this.generoPk = generoPk;
    }




}


