package com.udea.dto;
// Generated 26/11/2016 02:55:03 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reserva generated by hbm2java
 */
@Entity
@Table(name="RESERVA"
    ,schema="ROOT"
)
public class Reserva  implements java.io.Serializable {


     private String codigo;
     private String boletoFk;
     private String esatdo;
     private Date fecha;
     private Date hora;
     private String usuarioFk;

    public Reserva() {
    }

    public Reserva(String codigo, String boletoFk, String esatdo, Date fecha, Date hora, String usuarioFk) {
       this.codigo = codigo;
       this.boletoFk = boletoFk;
       this.esatdo = esatdo;
       this.fecha = fecha;
       this.hora = hora;
       this.usuarioFk = usuarioFk;
    }
   
     @Id 

    
    @Column(name="CODIGO", unique=true, nullable=false, length=15)
    @GeneratedValue(strategy = javax.persistence.GenerationType.IDENTITY)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="BOLETO_FK", nullable=false, length=15)
    public String getBoletoFk() {
        return this.boletoFk;
    }
    
    public void setBoletoFk(String boletoFk) {
        this.boletoFk = boletoFk;
    }

    
    @Column(name="ESATDO", nullable=false, length=50)
    public String getEsatdo() {
        return this.esatdo;
    }
    
    public void setEsatdo(String esatdo) {
        this.esatdo = esatdo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="HORA", nullable=false, length=8)
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }

    
    @Column(name="USUARIO_FK", nullable=false, length=15)
    public String getUsuarioFk() {
        return this.usuarioFk;
    }
    
    public void setUsuarioFk(String usuarioFk) {
        this.usuarioFk = usuarioFk;
    }




}


