package com.udea.dto;
// Generated 26/11/2016 02:55:03 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Sala generated by hbm2java
 */
@Entity
@Table(name="SALA"
    ,schema="ROOT"
)
public class Sala  implements java.io.Serializable {


     private String codigo;
     private String nombre;
     private String capacidad;
     private String sucursal;

    public Sala() {
    }

    public Sala(String codigo, String nombre, String capacidad, String sucursal) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.capacidad = capacidad;
       this.sucursal = sucursal;
    }
   
     @Id 

    
    @Column(name="CODIGO", unique=true, nullable=false, length=15)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="NOMBRE", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="CAPACIDAD", nullable=false, length=30)
    public String getCapacidad() {
        return this.capacidad;
    }
    
    public void setCapacidad(String capacidad) {
        this.capacidad = capacidad;
    }

    
    @Column(name="SUCURSAL", nullable=false, length=15)
    public String getSucursal() {
        return this.sucursal;
    }
    
    public void setSucursal(String sucursal) {
        this.sucursal = sucursal;
    }




}


