package com.udea.dto;
// Generated 26/11/2016 02:55:03 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Sucursal generated by hbm2java
 */
@Entity
@Table(name="SUCURSAL"
    ,schema="ROOT"
)
public class Sucursal  implements java.io.Serializable {


     private String codigo;
     private String nombre;
     private String ciudadFk;
     private String direccion;
     private String telefono;

    public Sucursal() {
    }

    public Sucursal(String codigo, String nombre, String ciudadFk, String direccion, String telefono) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.ciudadFk = ciudadFk;
       this.direccion = direccion;
       this.telefono = telefono;
    }
   
     @Id 

    
    @Column(name="CODIGO", unique=true, nullable=false, length=15)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="NOMBRE", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="CIUDAD_FK", nullable=false, length=15)
    public String getCiudadFk() {
        return this.ciudadFk;
    }
    
    public void setCiudadFk(String ciudadFk) {
        this.ciudadFk = ciudadFk;
    }

    
    @Column(name="DIRECCION", nullable=false, length=20)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="TELEFONO", nullable=false, length=12)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }




}


