package com.udea.dto;
// Generated 26/11/2016 02:55:03 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="USUARIO"
    ,schema="ROOT"
)
public class Usuario  implements java.io.Serializable {


     private String codigo;
     private String nombre;
     private String apellidos;
     private String tipodocumento;
     private String numerodocumento;
     private String contrasenia;
     private Date fechanacimiento;
     private String email;
     private String sexo;

    public Usuario() {
    }

    public Usuario(String codigo, String nombre, String apellidos, String tipodocumento, String numerodocumento, String contrasenia, Date fechanacimiento, String email, String sexo) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.tipodocumento = tipodocumento;
       this.numerodocumento = numerodocumento;
       this.contrasenia = contrasenia;
       this.fechanacimiento = fechanacimiento;
       this.email = email;
       this.sexo = sexo;
    }
   
     @Id 

    
    @Column(name="CODIGO", unique=true, nullable=false, length=15)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="NOMBRE", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="APELLIDOS", nullable=false, length=50)
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    
    @Column(name="TIPODOCUMENTO", nullable=false, length=3)
    public String getTipodocumento() {
        return this.tipodocumento;
    }
    
    public void setTipodocumento(String tipodocumento) {
        this.tipodocumento = tipodocumento;
    }

    
    @Column(name="NUMERODOCUMENTO", nullable=false, length=15)
    public String getNumerodocumento() {
        return this.numerodocumento;
    }
    
    public void setNumerodocumento(String numerodocumento) {
        this.numerodocumento = numerodocumento;
    }

    
    @Column(name="CONTRASENIA", nullable=false, length=20)
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHANACIMIENTO", nullable=false, length=10)
    public Date getFechanacimiento() {
        return this.fechanacimiento;
    }
    
    public void setFechanacimiento(Date fechanacimiento) {
        this.fechanacimiento = fechanacimiento;
    }

    
    @Column(name="EMAIL", nullable=false, length=30)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="SEXO", nullable=false, length=1)
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }




}


