package model;
// Generated 11-abr-2014 12:34:59 by Hibernate Tools 3.6.0



/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private long id;
     private Ciudad ciudad;
     private String nombre;
     private String documento;
     private String telefono;
     private String direccion;
     private String email;

    public Cliente() {
    }

	
    public Cliente(long id, Ciudad ciudad, String nombre, String documento) {
        this.id = id;
        this.ciudad = ciudad;
        this.nombre = nombre;
        this.documento = documento;
    }
    public Cliente(long id, Ciudad ciudad, String nombre, String documento, String telefono, String direccion, String email) {
       this.id = id;
       this.ciudad = ciudad;
       this.nombre = nombre;
       this.documento = documento;
       this.telefono = telefono;
       this.direccion = direccion;
       this.email = email;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Ciudad getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(Ciudad ciudad) {
        this.ciudad = ciudad;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(String documento) {
        this.documento = documento;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


